In [16]:
list_a=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
square=[]
for sq in list_a:
    if(4 %2 == 0 & 5%2==0):
        print(sq**2)
# print(square)        
        

In [17]:
b = [x**2 for x in range(1,21) if x%4==0 or x%5==0]
print(b)

[16, 25, 64, 100, 144, 225, 256, 400]


In [18]:
!conda create --name myenv python=3.9

zsh:1: command not found: conda


In [19]:
import numpy as np


In [20]:
a = np.array([1,2,3,4,5])


In [21]:
print(a)

[1 2 3 4 5]


In [23]:
type(a)

numpy.ndarray

In [3]:
import numpy as np
b = np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
c= np.ones((2,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
d = np.random.rand(2,3)
print(d)

[[0.8467103  0.69263052 0.97450415]
 [0.21960979 0.97622087 0.79649399]]


In [11]:
import numpy as np
e = np.random.seed(42)
print(d)

[[0.8467103  0.69263052 0.97450415]
 [0.21960979 0.97622087 0.79649399]]


In [33]:
import numpy as np
f = np.array([[1,2,3],[4,5,6],[6,4,6]])
#     print(f[1,2])
print(f[:,1])
print(f[1][2])

[2 5 4]
6


In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = b+a
print(c)

[5 7 9]


In [26]:
d = a+b
print(d)

[5 7 9]


In [28]:
e =np.sum(a)
print(e)

6


In [37]:
g = np.array([[1,2,3],[5,6,7]])
h = np.array([4,5,6])
i = g+h
print(i)

[[ 5  7  9]
 [ 9 11 13]]


In [42]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [46]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# print(a.shape)
# print(b.size)
a.shape

(2, 2)

In [51]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.concatenate((a,b),axis=0)
# print(c)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
a = np.array([[1,2],[3,4]])
condition  = a %2== 0
b = a[condition]
print(b)

[2 4]


In [59]:
np.sin(90)

0.8939966636005579

In [60]:
a = np.array([1,2,3,4])
np.save('data.npy',a)

In [61]:
b = np.load('data.npy')

In [62]:
b

array([1, 2, 3, 4])

In [68]:
a = np.array([1,2,3,4])
np.mean(a)
np.min(a)
np.median(a)
np.std(a)
# Spark


1.118033988749895

In [77]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
np.random.choice(a,size=3,replace=False)

array([14, 13,  5])

In [86]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.matmul(a,b)
np.linalg.det(a)

-2.0000000000000004

In [90]:
np.dot(a,b)
a.dot(b)

array([[19, 22],
       [43, 50]])

In [91]:
np.sort(a)

array([[1, 2],
       [3, 4]])

In [99]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
np.sort(a)[::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [100]:
mul_a = np.array([[1,2,3],[4,5,6],[6,4,6]])
type(mul_a)

numpy.ndarray

In [101]:
mul_a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 4, 6]])

In [102]:
mul_d = np.array([1,2,3],ndmin=5)
mul_d

array([[[[[1, 2, 3]]]]])

In [103]:
np.mat(mul_d)

matrix([[1, 2, 3]])

In [108]:
mul_d.ndim

5

In [111]:
array = ([1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18])
np.arange(1,28,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [124]:
np.empty(6)
np.empty(6,int)

array([4605801707965229684, 4604413880688763746, 4606952772638309444,
       4597080296720391648, 4606968235408075874, 4605349399640131377])

In [131]:
mask_array = np.linspace(4,50,24,dtype=int).reshape(4,-1)
mask_array

array([[ 4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])